// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbnBaVvH_kkZ5zu4BvGAP49VzJPUR8HBU',
    appId: '1:100724467097:web:418061c6ee63170bd7df08',
    messagingSenderId: '100724467097',
    projectId: 'fir-demo-8643b',
    authDomain: 'fir-demo-8643b.firebaseapp.com',
    storageBucket: 'fir-demo-8643b.firebasestorage.app',
    measurementId: 'G-T3NRK2ZLPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhONKhqaQDhJSmmprqeObAQCzu_8mLUA0',
    appId: '1:100724467097:android:2a621e2f0481957ad7df08',
    messagingSenderId: '100724467097',
    projectId: 'fir-demo-8643b',
    storageBucket: 'fir-demo-8643b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARI-P4zSVaFuLb2ni7pKYxdRz79gQRyTA',
    appId: '1:100724467097:ios:7124b738342c307fd7df08',
    messagingSenderId: '100724467097',
    projectId: 'fir-demo-8643b',
    storageBucket: 'fir-demo-8643b.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARI-P4zSVaFuLb2ni7pKYxdRz79gQRyTA',
    appId: '1:100724467097:ios:7124b738342c307fd7df08',
    messagingSenderId: '100724467097',
    projectId: 'fir-demo-8643b',
    storageBucket: 'fir-demo-8643b.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbnBaVvH_kkZ5zu4BvGAP49VzJPUR8HBU',
    appId: '1:100724467097:web:47828d4bd624216ed7df08',
    messagingSenderId: '100724467097',
    projectId: 'fir-demo-8643b',
    authDomain: 'fir-demo-8643b.firebaseapp.com',
    storageBucket: 'fir-demo-8643b.firebasestorage.app',
    measurementId: 'G-14RF2HZ8M0',
  );
}
